#!/usr/bin/env bash
# Syncs shared-ai-library to all supported AI CLI targets.
#
# Global targets:
#   ~/.opencode/         OpenCode
#   ~/.agents/agents           Antigravity
#   ~/.claude/           Claude Code
#   ~/.gemini/GEMINI.md  Gemini (personas only, compiled)
#
# Project-local (this repo only):
#   .opencode/agents → ../agents  (symlink, created once)
#   .opencode/skills → ../skills  (symlink, created once)
#   .github/copilot-instructions.md  (personas only, compiled)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REGISTRY_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

PERSONAS_DIR="$REGISTRY_DIR/personas"
AGENTS_DIR="$REGISTRY_DIR/agents"
SKILLS_DIR="$REGISTRY_DIR/skills"

OPENCODE_DIR="${OPENCODE_DIR:-$HOME/.opencode}"
ANTIGRAVITY_DIR="${ANTIGRAVITY_DIR:-$HOME/.agents}"
CLAUDE_DIR="${CLAUDE_DIR:-$HOME/.claude}"

# ── helpers ───────────────────────────────────────────────────────────────────

log() { printf '\033[1;34m[sync-ai]\033[0m %s\n' "$*"; }

strip_frontmatter() {
  awk 'BEGIN{fm=0} /^---$/{if(NR==1){fm=1;next}else if(fm){fm=0;next}} !fm' "$1"
}

sync_dir() {
  local src="$1" dest="$2" label="$3"
  mkdir -p "$dest"
  local count=0
  for f in "$src"/*.md; do
    [[ -f "$f" ]] || continue
    cp "$f" "$dest/$(basename "$f")"
    log "  → $dest/$(basename "$f")"
    ((count++))
  done
  log "Synced $count $label → $dest"
}

# ── .opencode symlinks (project-local, idempotent) ────────────────────────────

PROJECT_OPENCODE="$REGISTRY_DIR/.opencode"
mkdir -p "$PROJECT_OPENCODE"

if [[ ! -L "$PROJECT_OPENCODE/agents" ]]; then
  ln -s ../agents "$PROJECT_OPENCODE/agents"
  log "Created symlink → .opencode/agents"
fi
if [[ ! -L "$PROJECT_OPENCODE/skills" ]]; then
  ln -s ../skills "$PROJECT_OPENCODE/skills"
  log "Created symlink → .opencode/skills"
fi

# ── OpenCode (global) ─────────────────────────────────────────────────────────

sync_dir "$PERSONAS_DIR" "$OPENCODE_DIR/personas" "persona(s)"
sync_dir "$AGENTS_DIR"   "$OPENCODE_DIR/agents"   "agent(s)"
sync_dir "$SKILLS_DIR"   "$OPENCODE_DIR/skills"   "skill(s)"

# ── Antigravity (global) ──────────────────────────────────────────────────────

count=0
for f in "$AGENTS_DIR"/*.md; do
  [[ -f "$f" ]] || continue
  agent_name="$(basename "$f" .md)"
  dest="$ANTIGRAVITY_DIR/agents/$agent_name"
  mkdir -p "$dest"
  cp "$f" "$dest/agent.md"
  log "  → $dest/agent.md"
  ((count++))
done
log "Synced $count agent(s) → $ANTIGRAVITY_DIR/agents/"

count=0
for f in "$SKILLS_DIR"/*.md; do
  [[ -f "$f" ]] || continue
  skill_name="$(basename "$f" .md)"
  dest="$ANTIGRAVITY_DIR/skills/$skill_name"
  mkdir -p "$dest"
  cp "$f" "$dest/SKILL.md"
  log "  → $dest/SKILL.md"
  ((count++))
done
log "Synced $count skill(s) → $ANTIGRAVITY_DIR/skills/"

# ── Claude Code (global) ──────────────────────────────────────────────────────

sync_dir "$AGENTS_DIR" "$CLAUDE_DIR/agents" "agent(s)"

mkdir -p "$CLAUDE_DIR/commands"
count=0
for f in "$SKILLS_DIR"/*.md; do
  [[ -f "$f" ]] || continue
  cp "$f" "$CLAUDE_DIR/commands/$(basename "$f")"
  log "  → $CLAUDE_DIR/commands/$(basename "$f")"
  ((count++))
done
log "Synced $count skill(s) as commands → $CLAUDE_DIR/commands/"

# ── GitHub Copilot — personas only ───────────────────────────────────────────

COPILOT_FILE="$REGISTRY_DIR/.github/copilot-instructions.md"
mkdir -p "$(dirname "$COPILOT_FILE")"
{
  echo "<!-- AUTO-GENERATED by sync.sh — edit files in personas/ -->"
  echo ""
  for f in "$PERSONAS_DIR"/*.md; do
    [[ -f "$f" ]] || continue
    strip_frontmatter "$f"
    echo ""
  done
} > "$COPILOT_FILE"
log "Compiled personas → $COPILOT_FILE"

# ── Gemini — personas only ────────────────────────────────────────────────────

GEMINI_FILE="$HOME/.gemini/GEMINI.md"
mkdir -p "$(dirname "$GEMINI_FILE")"
{
  echo "<!-- AUTO-GENERATED by sync.sh — edit files in personas/ -->"
  echo ""
  for f in "$PERSONAS_DIR"/*.md; do
    [[ -f "$f" ]] || continue
    strip_frontmatter "$f"
    echo ""
  done
} > "$GEMINI_FILE"
log "Compiled personas → $GEMINI_FILE"

log "Done."
